### PR TITLE
Upgrade nom to 7.1.0

### PR DESCRIPTION
**Pull request by zsluedem**
The synxtax of nom is quite obsolete which use 4.0.0. And I found the link here https://github.com/Geal/nom would lead to user question of old version of nom.

Hope this can help.

### CODE REVIEW

**Comment by zsluedem** [comment]
@Rydgel

**Comment by Rydgel** [comment]
Thanks, looking at it today

**Comment by Rydgel** [comment]
@zsluedem thanks for the hard work, I put your name inside CONTRIBUTORS is that good for you?

**Comment by zsluedem** [comment]
> @zsluedem thanks for the hard work, I put your name inside CONTRIBUTORS is that good for you?

I am fine with that. Thanks.

**Pull request merged**
